SELECT 
  [GeographyKey], 
  [City], 
  [StateProvinceCode], 
  [StateProvinceName], 
  [CountryRegionCode], 
  [EnglishCountryRegionName], 
  [FrenchCountryRegionName], 
  [SalesTerritoryKey] 
FROM 
  [dbo].[DimGeography]